import pytest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time

s=Service('C:/Users/ereme/Downloads/chrome-win32/chrome-win32/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get("https://guru.qahacking.ru/")
time.sleep(1)
driver.maximize_window()
driver.find_element(By.CSS_SELECTOR, ".uk-navbar-nav > li:nth-child(1) > a").click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 1200)")
time.sleep(1)
driver.find_element(By.ID, "firstName").click()
driver.find_element(By.ID, "firstName").send_keys("Иван")
time.sleep(1)
driver.find_element(By.ID, "lastName").click()
driver.find_element(By.ID, "lastName").send_keys("Иванов")
time.sleep(1)
driver.find_element(By.ID, "userEmail").click()
driver.find_element(By.ID, "userEmail").send_keys("mailname@mail.ru")
time.sleep(1)
driver.find_element(By.ID, "sex-radio-3").click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 1600)")
time.sleep(1)
driver.find_element(By.ID, "userNumber").click()
driver.find_element(By.ID, "userNumber").send_keys("9008889900")
time.sleep(1)
driver.find_element(By.ID, "date").click()
driver.find_element(By.ID, "date").clear()
driver.find_element(By.ID, "date").send_keys("26.07.2023")
time.sleep(1)
driver.find_element(By.ID, "hobbies-checkbox-1").click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 2000)")
driver.find_element(By.ID, "currentAddress").click()
driver.find_element(By.ID, "currentAddress").send_keys("Omsk syty, Lenina strit, 5/2")
time.sleep(1)
driver.find_element(By.ID, "submit").click()
print("input data")
print("Process finished with exit code 0")